# Generated by Django 4.2.1 on 2023-05-25 20:59

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('profile_picture', models.ImageField(default='users/profile.png', upload_to=accounts.models.upload_to_profile_path)),
                ('cover_picture', models.ImageField(default='users/cover.png', upload_to=accounts.models.upload_to_cover_path)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship_status', models.CharField(choices=[('Ma', 'Married'), ('Si', 'Single'), ('Co', 'Committed'), ('Di', 'Divorced'), ('En', 'Engaged'), ('Se', 'Separated'), ('Oa', 'Open For All')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
