# Generated by Django 4.2.1 on 2023-05-25 21:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(default='users/cover.jpg', upload_to=accounts.models.upload_to_cover_path),
        ),
    ]
