# Generated by Django 4.2.1 on 2023-05-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('Ma', 'Married'), ('Si', 'Single'), ('Co', 'Committed'), ('Di', 'Divorced'), ('En', 'Engaged'), ('Se', 'Separated'), ('Oa', 'Open For All')], max_length=2, null=True),
        ),
    ]
